type InfluencerSuggestion = {
    id: number,
    name?: string,
    known_as?: string,
    x_handle: string,
    official_website?: string,
    bio?: string,
    quote?: string,
    profile_image?: string,
    banner_image?: string,
    country_location?: string,
    country_origin?: string,
    country_raised?: string,
    estimated_networth?: string,
    status: string,
    approved_at?: string,
    rejected_at?: string,
    rejected_reason?: string,
    user_id?: number,
}
